tasks:
  - before: curl https://get.modular.com | MODULAR_AUTH=mut_3e536625aa0a431b89738b61128657dc sh - && modular install mojo
  - before: >-
      echo 'export MODULAR_HOME="/home/gitpod/.modular"' >> ~/.bashrc &&
      echo 'export PATH="/home/gitpod/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc &&
      source ~/.bashrc
vscode:
  extensions:
    - "Codeium.codeium"
    - "modular-mojotools.vscode-mojo"
